// Generated by Wrangler by running `wrangler types`

interface Env {
	PASTE_KV: KVNamespace;
	GH_REPO_URL: "https://github.com/brendanv/paste-workers";
	AUTH_USERS: string;
	BASE_URL: string;
	DOMAIN: string;
}
